name: inset_field_shadow
description: "A customizable Flutter text field with inset shadow and support for FormField functionality."
version: 0.0.1
homepage: null
repository: https://github.com/HMZKA/inset_field_shadow
issue_tracker: https://github.com/HMZKA/inset_field_shadow/issues
license: MIT

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inset_box_shadow: ^1.0.8

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter: null
